-- Supabase schema for Digikoder Spirit
-- Run this in Supabase SQL editor

-- Use auth.users for authentication; create a profile table to store role
create table profiles (
  id uuid references auth.users(id) on delete cascade,
  email text,
  role text default 'user',
  created_at timestamptz default now(),
  primary key (id)
);

create table contents (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  type text not null,
  platform text,
  category text,
  description text,
  keywords text[],
  owner uuid references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index on contents(owner);

-- Enable RLS and minimal policies
alter table contents enable row level security;

-- Allow anyone to select (public read). Change to owner-only if you prefer private.
create policy "Public read" on contents for select using (true);

-- Only authenticated users can insert and owner must be auth.uid()
create policy "Insert own" on contents for insert using (auth.role() = 'authenticated') with check (owner = auth.uid());

-- Owners can update/delete their rows
create policy "Update own" on contents for update using (owner = auth.uid()) with check (owner = auth.uid());
create policy "Delete own" on contents for delete using (owner = auth.uid());

-- Create a profile for existing auth users automatically (Trigger)
create function public.handle_new_user() returns trigger language plpgsql as $$
begin
  insert into profiles(id, email, role) values (new.id, new.email, 'user');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute procedure public.handle_new_user();
